version: "3"
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}

  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command:
      - bash
      - -c
      - kafka-topics --create --topic ${TOPIC} --bootstrap-server=${KAFKA_BROKER}

  producer:
    build: ./producer # Make sure Dockerfile and code for producer is in /producer directory
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      TOPIC: ${TOPIC}
      PRODUCE_PORT: ${PRODUCE_PORT}

  consumer1:
    build: ./consumer1 # Make sure Dockerfile and code for consumer1 is in /consumer1 directory
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      TOPIC: ${TOPIC}

  consumer2:
    build: ./consumer2 # Make sure Dockerfile and code for consumer2 is in /consumer2 directory
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      TOPIC: ${TOPIC}
